language: python

python: '3.8'

install: pip install -r requirements.txt

services: sqlite3

env: DJANGO_SETTINGS_MODULE=blog.settings

before_script: python manage.py collectstatic

script: python manage.py test