language: python

python: '3.9'

install: pip install -r requirements.txt

services: sqlite3

before_script: python manage.py collectstatic

env: DJANGO_SETTINGS_MODULE=blog.travis

script: python manage.py test